src/components/tables/Tables.tsx, src/stories/Tables.stories.tsx
=> add table componnets for ui

deploy/lib/application-stack.ts, deploy/lib/pipeline-stack.ts, package.json, src/main.tsx, start.sh, vite.config.ts, yarn.lock
=> hotfix for deploy bug and testing

src/components/common/spinner/SpinnerWithText.tsx, src/components/dialogs/SimpleDialog.tsx, src/components/files/index.tsx, src/components/layouts/MainLayout.tsx, src/components/layouts/lab/LibraryLayout.tsx, src/components/navigation/header/index.tsx, src/components/navigation/navbar/SideNavBar.tsx, src/components/tables/Pagination.tsx, src/components/tables/Table.tsx, src/hooks/useQueryParams.ts, src/modules/lab/library/workflow/components/PortalRunIdDropdown.tsx, src/modules/lab/library/workflow/components/WorkflowVersion.tsx, src/modules/lab/library/workflow/index.tsx, src/modules/lab/metadata/components/LibraryAPITable.tsx, src/modules/lab/metadata/components/MetadataFilterDropdown.tsx, src/modules/lab/metadata/components/MetadataTable.tsx, src/modules/lab/metadata/components/SubjectAPITable.tsx
- Remodel the metadata filter table
- Fix lab/workflow API to catch invalid protalRunId mismatch
- Fix preview filetype whitelist
=> Feat: Enhancement

src/components/common/datepicker/DateRangePicker.tsx, src/components/common/drawers/sideDrawer.tsx, src/components/common/select/IconMultipleSelect.tsx, src/components/common/tooltips/index.tsx, src/context/AmplifyAuthContext.tsx, src/modules/runs/components/StatusTimeline.tsx, src/modules/runs/components/WorkflowRunDetailsDrawer.tsx, src/modules/runs/components/WorkflowRunTable.tsx, src/modules/runs/components/WorkflowRunTableHeader.tsx, src/modules/runs/tables/WorkflowRunTable.tsx, src/utils/commonUtils.ts
1. fix drawer issues from conflict of the query params and states
=> fix the side  drawer flash issue and upgrade some ui

src/api/file.ts, src/api/metadata.ts, src/api/workflow.ts, src/components/common/error/DetailedErrorBoundary.tsx, src/components/common/json-to-table/json-to-table.tsx, src/components/layouts/lab/components/LibraryBreadCrumb.tsx, src/components/tables/GroupedRowTable.tsx, src/modules/files/components/FileAPITable.tsx, src/modules/lab/components/individual/IndividualListAPITable.tsx, src/modules/lab/components/library/LibraryAnalysisReportTable.tsx, src/modules/lab/components/library/LibraryListAPITable.tsx, src/modules/lab/components/library/LibraryTableDetails.tsx, src/modules/lab/components/library/PortalRunIdDropdown.tsx, src/modules/lab/components/sample/SampleListAPITable.tsx, src/modules/lab/components/subject/SubjectListAPITable.tsx, src/modules/lab/pages/library/LibraryOverview.tsx, src/modules/lab/pages/library/LibraryWorkflow.tsx, src/utils/constant.ts
Added expected files from each workflow type in the Library Overview page.
=> File Overview Highlight

src/components/common/json-to-table/json-to-nested-list.tsx, src/modules/files/components/FileAPITable.tsx, src/modules/files/pages/files.tsx, src/modules/lab/components/library/LibraryAnalysisReportTable.tsx, src/modules/runs/workflowRuns/components/StatusTimeline.tsx
- Refine file filters for library analysis table
- Linkage from s3uri workflow payload to `/files` page
=> Refine: Analysis table and Link s3 uri to `/files` page

src/api/metadata.ts, src/api/types/file.d.ts, src/api/types/metadata.d.ts, src/api/types/workflow.d.ts, src/components/layouts/lab/components/LibraryBreadCrumb.tsx, src/components/layouts/lab/components/LibrarySideNavBar.tsx, src/components/tables/Table.tsx, src/modules/lab/components/library/LibraryAnalysisReportTable.tsx, src/modules/lab/components/library/LibraryListAPITable.tsx, src/modules/lab/components/library/LibraryTableDetails.tsx, src/modules/lab/components/library/PortalRunIdDropdown.tsx, src/modules/lab/components/library/WorkflowVersion.tsx, src/modules/lab/pages/library/LibraryHistory.tsx, src/modules/lab/pages/library/LibraryOverview.tsx, src/modules/lab/pages/library/LibraryWorkflow.tsx, src/modules/lab/routes.tsx, src/modules/runs/workflowRuns/components/WorkflowRunDetailsDrawer.tsx
- Convert the use of `libraryId` in path to `libraryOrcabusId`
- Added library history page
=> Feat: Metadata OrcabusId and Library History

src/modules/runs/components/workflowRuns/WorkflowRunDetailsTable.tsx
replace library with orcabusId in lib links
=> replace library with orcabusId in lib links

src/components/common/badges/Badge.tsx, src/components/common/json-to-table/json-display.tsx, src/components/common/timelines/Timeline.tsx, src/modules/runs/components/workflowRuns/WorkflowRunTimeline.tsx
=> fix ui format bugs for timeline and payload

src/api/metadata.ts, src/api/types/metadata.d.ts, src/components/layouts/lab/LibraryLayout.tsx, src/components/layouts/lab/components/LibraryBreadCrumb.tsx, src/components/navigation/breadcrumbs/index.tsx, src/components/navigation/navbar/ModuleNavBar.tsx, src/modules/lab/components/subject/SubjectListAPITable.tsx, src/modules/lab/pages/Metadata.tsx, src/modules/lab/pages/Sync.tsx, src/modules/lab/routes.tsx
- add sync page
- Minor CSS update on Library layout / breadcrumb
=> Feat: Add Trigger Sync Metadata Page

eslint.config.js, src/api/metadata.ts, src/api/utils.ts, src/modules/lab/components/contact/utils.tsx, src/modules/lab/components/individual/IndividualListAPITable.tsx, src/modules/lab/components/individual/utils.tsx, src/modules/lab/components/library/LibraryListAPITable.tsx, src/modules/lab/components/library/LibraryTableFilter.tsx, src/modules/lab/components/library/utils.tsx, src/modules/lab/components/project/ProjectListAPITable.tsx, src/modules/lab/components/project/ProjectTableFilter.tsx, src/modules/lab/components/project/utils.tsx, src/modules/lab/components/sample/SampleListAPITable.tsx, src/modules/lab/components/sample/SampleTableFilter.tsx, src/modules/lab/components/sample/utils.tsx, src/modules/lab/components/subject/SubjectListAPITable.tsx, src/modules/lab/components/subject/SubjectTableFilter.tsx, src/modules/lab/components/subject/utils.tsx, src/modules/lab/components/utils.tsx, src/modules/lab/pages/Metadata.tsx
- Refactor/Centralized to reuse metadata column component across tables
- Add the project page to the table tabs
=> Chore: Refactor Metadata Table Component 

src/api/types/metadata.d.ts, src/api/types/workflow.d.ts, src/modules/lab/components/library/LibraryTableFilter.tsx, src/modules/lab/components/project/ProjectTableFilter.tsx, src/modules/lab/components/sample/SampleTableFilter.tsx, src/modules/lab/components/subject/SubjectTableFilter.tsx
- Fix filtering library based on project_id
- update openapi types
Resolves #83
=> Fix: Project Based Library Filter

src/components/common/dropdowns/Dropdown.tsx, src/components/dialogs/SimpleDialog.tsx, src/components/files/ImageViewer.tsx, src/components/files/igv/IgvJs.tsx, src/modules/files/components/FileAPITable.tsx, src/modules/files/components/FilePreviewDrawer.tsx, src/modules/files/pages/files.tsx, src/modules/lab/pages/library/LibraryWorkflow.tsx, src/modules/runs/components/workflowRuns/WorkflowRunTimeline.tsx
- Add predefined filtered on file page
- Allow multiple filters for buckets/s3-keys
- File filter in wfr-library is default to wildcard
=> Feat: Refine File Table/Page

src/api/types/sequence-run.d.ts, src/api/types/workflow.d.ts, src/api/workflow.ts, src/modules/runs/components/workflowRuns/WorkflowRunFilterHeader.tsx
hotfix for sequence runs and workflow runs api modification
=> hotfix for api change

src/components/layouts/lab/components/LibrarySideNavBar.tsx, src/modules/lab/components/library/LibraryAnalysisReportTable.tsx, src/modules/lab/components/library/PortalRunIdDropdown.tsx, src/modules/lab/components/library/WorkflowVersion.tsx, src/modules/lab/pages/library/LibraryOverview.tsx, src/modules/runs/components/workflowRuns/WorkflowRunTable.tsx
Followup after https://github.com/umccr/orcabus/pull/784
=> chore: Remove temporary workaround for `orcabus_id` prefix

deploy/config.ts, deploy/lambda/env_config_and_cdn_refresh.py, src/api/sscheck.ts, src/components/layouts/sscheck/SSCheckLayout.tsx, src/config.ts, src/modules/sscheck/components/SSChecker.tsx, src/modules/sscheck/components/SuccessResponse.tsx, src/modules/sscheck/pages/SSCheck.tsx, src/modules/sscheck/routes.tsx, src/router/modules.ts, src/utils/navigation.ts, start.sh
=> Feat: add new sscheck page

src/api/file.ts, src/api/sequenceRun.ts, src/api/workflow.ts, src/modules/runs/components/workflowRuns/WorkflowRunDetailsTable.tsx
=> Fix: Throw Error Unsuccessful Response

.gitignore, .pre-commit-config.yaml, Makefile, package.json, src/components/common/spinner/SpinnerWithText.tsx, src/components/files/igv/IgvDesktop.tsx, src/components/files/igv/IgvJs.tsx, src/modules/files/components/FileAPITable.tsx, src/modules/files/components/FileDownloadButton.tsx, src/modules/files/components/FilePreviewDrawer.tsx, src/modules/lab/components/individual/IndividualListAPITable.tsx, src/modules/lab/components/individual/IndividualTableFilter.tsx, src/modules/lab/components/individual/utils.tsx, src/modules/lab/components/library/LibraryListAPITable.tsx, src/modules/lab/components/library/LibraryTableFilter.tsx, src/modules/lab/components/library/WorkflowVersion.tsx, src/modules/lab/components/library/utils.tsx, src/modules/lab/components/project/ProjectListAPITable.tsx, src/modules/lab/components/project/ProjectTableFilter.tsx, src/modules/lab/components/sample/SampleListAPITable.tsx, src/modules/lab/components/sample/SampleTableFilter.tsx, src/modules/lab/components/subject/SubjectListAPITable.tsx, src/modules/lab/components/subject/SubjectTableFilter.tsx, src/modules/lab/pages/library/LibraryWorkflow.tsx, src/modules/runs/components/workflowRuns/WorkflowRunContext.tsx, src/modules/runs/components/workflowRuns/WorkflowRunTimeline.tsx, tsconfig.app.json
- Add `make deploy-dev` for quick dev deployment
- CSS Update on s3 path [#slack-thread](https://umccr.slack.com/archives/C03ABJTSN7J/p1737071864940699?thread_ts=1732507390.208029&cid=C03ABJTSN7J)
- Add type check `yarn tsc-check` will be used for backend API check compatibility. NOTE: `./stories` path is excluded from the check
- Add IGV js init loader and minor CSS update
- Add `OverrideCycle` column in Library table
=> Chore: Miscellaneous Enhancement

Makefile, deploy/lib/pipeline-stack.ts, src/modules/lab/components/project/ProjectTableFilter.tsx, src/modules/lab/pages/library/LibraryWorkflow.tsx
- Fix workflow file null error
- Reshuffle testing backend API type test before GAMMA deployment
- Project Filter fix
Fix #108
=> Fix: Display Error

deploy/package.json, deploy/yarn.lock
update the deploy dependents to fix security alerts
=> update deploy dependents for security alerts

src/components/common/badges/Badge.tsx, src/components/common/badges/StatusBadge.tsx, src/components/common/badges/index.tsx, src/main.tsx, src/modules/runs/components/sequenceRuns/SequenceRunTimeline.tsx, src/modules/runs/components/workflowRuns/WorkflowRunTimeline.tsx, src/modules/runs/index.tsx, src/utils/navigation.ts, src/utils/statusUtils.ts, vite.config.ts
1. quick fix build error in router path
2. fix build warning of "statusBackgroundColor" cycle dependency
3. fix ts-check warning of Badges by creating a independent 'statusUtils' files
4. add `v7_relativeSplatPath: true, v7_startTransition: true,` for router warning
=> fix build error and warnings

src/components/files/igv/IgvDesktop.tsx, src/components/files/igv/IgvJs.tsx, src/modules/files/components/FileAPITable.tsx
=> Feat: extra igv desktop button

src/modules/runs/components/sequenceRuns/SequenceRunTable.tsx
just add qc report link to srm table
resolve https://github.com/umccr/orca-ui/issues/118
it will redirect to filemanager - search "*{instrumentRunId}_multiqc_report.html" for key word
resolve https://github.com/umccr/orca-ui/issues/118
=> add action button for qc report link

src/components/layouts/lab/components/LibrarySideNavBar.tsx, src/components/layouts/runs/RunsModuleLayout.tsx, src/components/layouts/runs/RunsSideNavBar.tsx, src/components/navigation/navbar/ModuleNavBar.tsx
local storage for module bar close/expand preference
=> add storage for module bar preference

src/api/workflow.ts, src/components/common/dialogs/SimpleDialog.tsx, src/components/common/json-to-table/json-to-table.tsx, src/components/common/tooltips/index.tsx, src/components/layouts/lab/LibraryLayout.tsx, src/components/navigation/breadcrumbs/index.tsx, src/components/tables/GroupedRowTable.tsx, src/modules/files/components/FileAPITable.tsx, src/modules/files/components/InputBadgeBox.tsx, src/modules/lab/components/library/LibraryAnalysisReportTable.tsx, src/modules/lab/components/library/LibraryTableDetails.tsx, src/modules/lab/components/library/PortalRunIdDropdown.tsx, src/modules/lab/components/library/WorkflowDialogDetail.tsx, src/modules/lab/pages/library/LibraryWorkflow.tsx, src/modules/runs/components/workflowRuns/WorkflowRunDetailsTable.tsx
- filer out `/work/` directory in overview page
- Multiple run warnings for multiple portalRunId workflows
- CSS updates across components
Partially resolves #119
=> Chore: CSS and Miscellaneous Updates

src/context/AmplifyAuthContext.tsx
Fix the bug when logout, singin page auth error
=> Fix: add theme setting exception when authentication state

src/components/common/accordion/Accordion.tsx, src/components/common/error/DetailedErrorBoundary.tsx, src/modules/lab/components/library/LibraryAnalysisReportTable.tsx, src/modules/lab/components/library/LibraryLinkTable.tsx, src/modules/lab/components/library/LibraryListAPITable.tsx, src/modules/lab/components/sample/SampleListAPITable.tsx, src/modules/lab/components/subject/SubjectListAPITable.tsx, src/modules/lab/layouts/components/LibraryDetailBar.tsx
=> Chore: Refine Library Overview Page

src/modules/lab/components/library/LibraryAnalysisReportTable.tsx
=> Fix: SASH Filter

src/modules/runs/components/sequenceRuns/SequenceRunTable.tsx
fix experiment nameto allow link to detail page event if experiment name is not define
=> fix experiment name

src/modules/files/components/InputBadgeBox.tsx, src/modules/files/components/utils.ts, src/modules/files/pages/files.tsx, src/modules/lab/components/library/LibraryAnalysisReportTable.tsx, src/modules/lab/pages/library/LibraryWorkflow.tsx
- Mainly adding `key` as the props to force component to re-render when the orcabusId has change
- Add icon to search button when needed
- fix CSS tooltip bug
=> Fix: Reset state on redirect

src/components/common/sidebar/SideBar.tsx, src/components/tables/ListTable.tsx, src/modules/runs/components/sequenceRuns/SequenceRunDetailsActions.tsx, src/modules/runs/components/sequenceRuns/SequenceRunDetailsHeader.tsx, src/modules/runs/components/sequenceRuns/SequenceRunSampleSheetViewer.tsx, src/modules/runs/components/sequenceRuns/SequenceRunWorkflowRunsStats.tsx, src/modules/runs/components/sequenceRuns/SequenceRundetailsTimeline.tsx, src/modules/runs/components/workflowRuns/WorkflowRunDetailsHeader.tsx, src/modules/runs/pages/SequenceRunSampleSheet.tsx
Fix bugs for recent upgrade:
Preview at Dev: https://orcaui.dev.umccr.org/runs/sequence
1. remove state update button for not valid states
2. fix the sample sheet page error when samplesheet content is null
3. Add and fix the 'dark' style for some new components to fit overall styles
=> fix bugs in srm state and samplesheet

src/modules/lab/components/library/LibraryAnalysisReportTable.tsx
Add a `div` wrapper with orcabusId with key, to force re-render when the key has changed
=> Fix: Rerender on orcabusId change

src/components/files/index.tsx, src/modules/files/components/FileAPITable.tsx, src/modules/lab/components/library/LibraryAnalysisReportTable.tsx, src/modules/lab/pages/library/LibraryWorkflow.tsx
- Add `work` exclusion key filter
- Add view with or without key prefix in library workflow file table
- Allow download for `.gz` file
=> Feat: Refine File Viewing

src/modules/runs/components/sequenceRuns/SequenceRunWorkflowRuns.tsx, src/modules/runs/components/sequenceRuns/SequenceRunWorkflowRunsStats.tsx, src/modules/runs/pages/SequenceRunSampleSheet.tsx
solve #155 
couple with backend fix: https://github.com/umccr/orcabus/pull/940
preview in dev: https://orcaui.dev.umccr.org/runs/sequence/seq.01JP9PHN4GKJ094BRRNYXSN9KW/workflowruns
preview indev:https://orcaui.dev.umccr.org/runs/sequence/seq.01JP9FSH7FPP4050G71CEA92MG/workflowruns?page=1&workflowRunStatus=succeeded
results without duplicates:
=> SRM workflowruns linking bugs fix

deploy/config.ts, src/context/AmplifyAuthContext.tsx
Solve https://github.com/umccr/orca-ui/issues/161
Add portal alias to orcabus UI
=> add alias of portal domain

package.json, src/components/common/datepicker/DateSinglePicker.tsx, src/components/common/datepicker/index.ts, src/components/common/select/Select.tsx, src/components/common/select/index.tsx, src/modules/orcavault/api/lims.ts, src/modules/orcavault/components/GraphqlFilter.tsx, src/modules/orcavault/components/lims/LimsTable.tsx, src/modules/orcavault/layouts/SideBar.tsx, src/modules/orcavault/pages/Lims.tsx, src/modules/orcavault/routes.tsx, src/router/modules.ts, src/utils/appURLs.ts, src/utils/navigation.ts, yarn.lock
- added LIMS view table from orcavault
=> Feat: Initial OrcaVault Warehouse Page

src/modules/runs/components/sequenceRuns/SequenceRunTable.tsx
=> Feature: qlims metric shortcut

src/modules/lab/components/library/LibraryAnalysisReportTable.tsx, src/modules/lab/components/library/WorkflowDialogDetail.tsx, src/modules/lab/pages/library/LibraryWorkflow.tsx
=> Feat: filter out results from non SUCCEEDED wrf_run

deploy/lib/pipeline-stack.ts
=> Chore: Infrastructure Manual Approval Order

src/components/files/igv/IgvJs.tsx, src/components/files/igv/genomes.ts, src/components/files/igv/utils.ts
- Update IGV config 
- Fix unresolved type check
=> Fix igv config

src/modules/orcavault/components/GraphqlFilter.tsx
Remove appsync filter name that is not compatible with postgraphile
=> orcavault fix filtering option

deploy/lambda/env_config_and_cdn_refresh.py
Related #201 - I forgot to set the environment variable in the lambda function.
* Add htsget url to env config lambda function.
=> fix: update env config lambda function
